con4gisProjectsBundle:
    path: /con4gis/brick_ajax_api/{module}/{action}
    defaults:
        _scope: frontend
        _controller: "con4gisProjectsBundle:Ajax:ajax"
    requirements:
        module: '\d+'
        action: '.*'
con4gis_get_address:
    path: /con4gis/get_address/{profileId}/{lat}/{lon}
    defaults:
        _scope: frontend
        _controller: "con4gisProjectsBundle:Ajax:getAddress"
    requirements:
        profileId: '\d+'
        lat: '.*'
        lon: '.*'
