con4gisProjectsBundle:
    path: /con4gis/brick_ajax_api/{language}/{module}/{action}
    defaults:
        _scope: frontend
        _controller: "con4gisProjectsBundle:Ajax:ajax"
    requirements:
        module: '\d+'
        action: '.*'

editortab_service:
    path: /con4gis/editorTabService/{id}
    defaults:
        _scope: frontend
        _controller: "con4gisProjectsBundle:Ajax:editor"
    requirements:
        id: '\d+'
    methods: [GET, PUT, DELETE]

editortab_service_post:
    path: /con4gis/editorTabService
    defaults:
        _scope: frontend
        _controller: "con4gisProjectsBundle:Ajax:editorPost"
    methods: [POST]

con4gis_get_address:
    path: /con4gis/get_address/{profileId}/{lat}/{lon}
    defaults:
        _scope: frontend
        _controller: "con4gisProjectsBundle:Ajax:getAddress"
    requirements:
        profileId: '\d+'
        lat: '.*'
        lon: '.*'

con4gis_brick_file_upload:
    path: /con4gis/upload_file
    defaults:
        _scope: frontend
        _controller: "con4gisProjectsBundle:Ajax:upload"
    methods: [POST]