con4gisProjectsBundle:
    path: /con4gis/brick_ajax_api/{module}/{action}
    defaults:
        _scope: frontend
        _controller: "con4gisProjectsBundle:Ajax:ajax"
    requirements:
        module: '\d+'
        action: '.*'

