con4gisProjectsBundle:
    path: /con4gis/brick_ajax_api/{language}/{classname}/{module}/{action}
    controller: con4gis\ProjectsBundle\Controller\AjaxController::ajaxAction
    methods: [ GET, PUT ]
    requirements:
        module: '\d+'
        action: '.*'

editortab_service:
    path: /con4gis/editorTabService/{id}
    controller: con4gis\ProjectsBundle\Controller\AjaxController::editorAction
    requirements:
        id: '\d+'
    methods: [GET, PUT, DELETE]

editortab_service_post:
    path: /con4gis/editorTabService
    controller: con4gis\ProjectsBundle\Controller\AjaxController::editorPostAction
    methods: [POST]

con4gis_get_address:
    path: /con4gis/get_address/{profileId}/{lat}/{lon}
    controller: con4gis\ProjectsBundle\Controller\AjaxController::getAddressAction
    requirements:
        profileId: '\d+'
        lat: '.*'
        lon: '.*'

con4gis_brick_file_upload:
    path: /con4gis/upload_file
    controller: con4gis\ProjectsBundle\Controller\AjaxController::uploadAction
    methods: [POST]