services:
    _defaults:
        autowire: true
        autoconfigure: true

    con4gis\ProjectsBundle\Controller\AjaxController:
        arguments:
            - '%kernel.project_dir%'
            - "@session"
            - "@contao.framework"
        public: true
        class: con4gis\ProjectsBundle\Controller\AjaxController